Make aggregator work with new plugins extensing blueocean
New plugins that define dependency on blueocean aggregator fail to start
duing `mvn hpi:run` with error:

WARNING: Failed to load
org.jenkinsci.plugins.workflow.steps.scm.GenericSCMStep$DescriptorImpl
java.lang.NoClassDefFoundError:
org/jenkinsci/plugins/structs/describable/UninstantiatedDescribable
  at java.lang.Class.getDeclaredMethods0(Native Method)

Reason it fails is due to order in which dependencies are resolved by
mvn hpi:run where it resolves structs 1.2 during loading scm-api which
depends on junit and it depends on structs 1.2. But structs 1.2 doesn't
have UninstantiatedDescribable.